# Generated by Django 4.1.9 on 2023-07-16 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='PublishingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Издательство',
                'verbose_name_plural': 'Издательства',
            },
        ),
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('language', models.CharField(choices=[(None, 'Выберите язык:'), ('ru', 'русский'), ('en', 'английский')], max_length=50, verbose_name='Язык')),
                ('binding', models.CharField(choices=[(None, 'Выберите тип обложки:'), ('solid', 'твёрдая'), ('soft', 'мягкая')], max_length=50, verbose_name='Тип обложки')),
                ('pages', models.PositiveIntegerField(verbose_name='Количество страниц')),
                ('year', models.PositiveIntegerField(verbose_name='Год издания')),
                ('image', models.ImageField(blank=True, default='book-default.png', upload_to='images/%Y/%m/%d/', verbose_name='Изображение')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('author', models.ManyToManyField(to='books.authormodel')),
                ('category', models.ManyToManyField(to='books.categorymodel')),
                ('publishing', models.ManyToManyField(to='books.publishingmodel')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
